image:
  repository: crproxy.trafficmanager.net:5000/kubernetes/heapster

command:
- "/heapster"
- "--source=kubernetes:https://kubernetes.default"
- "--sink=influxdb:http://influxdb-influxdb.{MONITOR_CLUSTER_NS}:8086"

resizer:
  image:
    repository: crproxy.trafficmanager.net:6000/google_containers/addon-resizer
    tag: 1.7
