# StorageClass
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
  namespace: {{ .Values.common.namespace }}
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Premium_LRS
  location: {{ .Values.elasticsearch.data.location }}
  storageAccount: {{ .Values.elasticsearch.data.storageAccount }}
