apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" .}}-discovery
  namespace: {{ .Values.common.namespace }}
  labels:
    component: {{template "fullname" .}}
    role: master
spec:
  selector:
    component: {{template "fullname" .}}
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
