apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" .}}
  namespace: {{ .Values.common.namespace }}
  labels:
    component: {{template "fullname" .}}
    role: client
spec:
  type: {{ .Values.elasticsearch.service.type }}
  selector:
    component: {{template "fullname" .}}
    role: client
  ports:
  - name: http
    port: {{ .Values.elasticsearch.service.httpPort }}
    targetPort: 9200
    protocol: TCP
  - name: transport
    port: {{ .Values.elasticsearch.service.transportPort }}
    targetPort: 9300
    protocol: TCP
