# Default values for kibana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
common:
  namespace: elk-cluster-ns
  secretName: azure-registry
  registry: elkacr.azurecr.io
nameOverride: kibana
kibana:
  replicaCount: 2
  image:
    tag: 1.0.0
    pullPolicy: Always
  service:
    name: kibana
    type: LoadBalancer
    port: 80
