filebeat.registry_file: /var/log/containers/filebeat_registry

filebeat.prospectors:
-
  paths:
    - "/var/log/*.log"
    - "/var/log/containers/*.log"
    - "/var/log/pods/*.log"
    - "/var/lib/docker/containers/*.log"
  fields:
    host: ${FILEBEAT_HOST:${HOSTNAME}}
  fields_under_root: true

output.logstash:
    hosts: ["logstash:5043"]
    timeout: 15
# Available log levels are: critical, error, warning, info, debug
logging.level: info