apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    component: {{ template "fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 5601
    protocol: TCP
  selector:
    component: {{ template "fullname" . }}
